name       : mongodb-compass
version    : 1.39.0
release    : 13
source     :
    - https://github.com/mongodb-js/compass/archive/refs/tags/v1.39.0.tar.gz : dc9953c0184f22d86c0bfd853af5cd39580cfd1f89a2dc1f82fbb3941e13965f
license    : SSPL-1.0
component  : database
summary    : MongoDB management GUI
description: |
    MongoDB Compass is a visual manager for MongoDB.
networking : yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - pkgconfig(libdrm)
    - pkgconfig(libsecret-1)
    - git
    - nodejs
rundeps    :
    - nodejs
setup      : |
    # Disable husky command
    sed -i '/husky install/d' 'package.json'

    # Run the first part of npm run bootstrap
    npm install

    # Run the second part of npm run bootstrap
    npx lerna run bootstrap --stream

    %patch -p1 < $pkgfiles/Package-only-Solus-bits.patch
build      : |
    NODE_ENV=production npm run package-compass
install    : |
    install -dm00755 $installdir/usr/share
    cp -a 'packages/compass/dist/MongoDB Compass-linux-x64' $installdir/usr/share/mongodb-compass
    install -dm00755 $installdir/usr/bin
    ln -s '/usr/share/mongodb-compass/MongoDB Compass' $installdir/usr/bin/mongodb-compass

    install -Dm00644 $pkgfiles/mongodb-compass.desktop -t $installdir/usr/share/applications
    install -Dm00644 packages/compass/app-icons/linux/mongodb-compass.png -t $installdir/usr/share/pixmaps
