name       : mongodb-compass
version    : 1.21.2
release    : 2
source     :
    - https://github.com/mongodb-js/compass/archive/v1.21.2.tar.gz : b5b221aa3d91a8a4e6aa7f3194592f523e59aa56aca00a2a5e9493a4f9cced4e
license    : SSPL-1.0
component  : database
summary    : MongoDB management GUI
description: |
    MongoDB Compass is a visual manager for MongoDB.
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(com_err)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - cups-devel
    - git
    - nodejs
rundeps    :
    - gnome-keyring
    - nodejs
setup      : |
    npm install
    %patch -p1 < $pkgfiles/Package-only-Solus-bits.patch
build      : |
    NODE_ENV=production npm run-script release compass
install    : |
    rm 'dist/MongoDB Compass-linux-x64/LICENSES.chromium.html'

    install -dm00755 $installdir/usr/share
    cp -a 'dist/MongoDB Compass-linux-x64' $installdir/usr/share/mongodb-compass
    install -dm00755 $installdir/usr/bin
    ln -s '/usr/share/mongodb-compass/MongoDB Compass' $installdir/usr/bin/mongodb-compass

    install -Dm00644 $pkgfiles/mongodb-compass.desktop -t $installdir/usr/share/applications
    install -Dm00644 src/app/images/linux/mongodb-compass.png -t $installdir/usr/share/pixmaps
