name       : mongodb-compass
version    : 1.24.6
release    : 6
source     :
    - https://github.com/mongodb-js/compass/archive/v1.24.6.tar.gz : 9495eb33fdbab2bdfcce217b20b2d47ba1028fdabcb3f406a2693a0c0417fb55
license    : SSPL-1.0
component  : database
summary    : MongoDB management GUI
description: |
    MongoDB Compass is a visual manager for MongoDB.
networking : yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - git
    - nodejs
rundeps    :
    - gnome-keyring
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/Remove-Node-version-check.patch
    npm install
    %patch -p1 < $pkgfiles/Package-only-Solus-bits.patch
build      : |
    NODE_ENV=production npm run release-evergreen compass
install    : |
    rm 'dist/MongoDB Compass-linux-x64/LICENSES.chromium.html'

    install -dm00755 $installdir/usr/share
    cp -a 'dist/MongoDB Compass-linux-x64' $installdir/usr/share/mongodb-compass
    install -dm00755 $installdir/usr/bin
    ln -s '/usr/share/mongodb-compass/MongoDB Compass' $installdir/usr/bin/mongodb-compass

    install -Dm00644 $pkgfiles/mongodb-compass.desktop -t $installdir/usr/share/applications
    install -Dm00644 src/app/images/linux/mongodb-compass.png -t $installdir/usr/share/pixmaps
